import { spawnSync } from 'node:child_process'
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { resolve, join, relative, dirname } from 'node:path'
import { parseExperienceYaml } from '@openexpertise/schema'
import type { Logger } from 'pino'

export interface SubmitOpts {
  path?: string
  tags?: string
  name?: string
  ref?: string
  subpath?: string
  description?: string
  dryRun?: boolean
  output?: string
  logger: Logger
}

const GREEN = '\x1b[32m'
const YELLOW = '\x1b[33m'
const RED = '\x1b[31m'
const DIM = '\x1b[2m'
const BOLD = '\x1b[1m'
const RESET = '\x1b[0m'

interface GitRemote {
  owner: string
  repo: string
}

function detectGitRemote(repoPath: string): GitRemote | null {
  const r = spawnSync('git', ['-C', repoPath, 'remote', 'get-url', 'origin'], {
    encoding: 'utf8',
    timeout: 5000,
  })
  if (r.status !== 0) return null
  const url = r.stdout.trim()
  // Match both https://github.com/owner/repo(.git) and git@github.com:owner/repo(.git)
  const match = url.match(/github\.com[:/]([^/]+?)\/([^/.\n]+?)(?:\.git)?$/)
  if (!match || !match[1] || !match[2]) return null
  return { owner: match[1], repo: match[2] }
}

interface GitRef {
  ref: string
  isTag: boolean
}

function detectGitRef(repoPath: string): GitRef {
  // First try: tag at HEAD
  const tagR = spawnSync('git', ['-C', repoPath, 'describe', '--exact-match', '--tags', 'HEAD'], {
    encoding: 'utf8',
    timeout: 5000,
  })
  if (tagR.status === 0) {
    return { ref: tagR.stdout.trim(), isTag: true }
  }
  // Fallback: branch name
  const branchR = spawnSync('git', ['-C', repoPath, 'rev-parse', '--abbrev-ref', 'HEAD'], {
    encoding: 'utf8',
    timeout: 5000,
  })
  if (branchR.status === 0) {
    const ref = branchR.stdout.trim()
    return { ref: ref === 'HEAD' ? 'main' : ref, isTag: false }
  }
  return { ref: 'main', isTag: false }
}

function detectSubpath(repoPath: string, yamlPath: string): string {
  const rootR = spawnSync('git', ['-C', repoPath, 'rev-parse', '--show-toplevel'], {
    encoding: 'utf8',
    timeout: 5000,
  })
  if (rootR.status !== 0) return ''
  const root = rootR.stdout.trim()
  const yamlDir = dirname(yamlPath)
  if (yamlDir === root) return ''
  return relative(root, yamlDir)
}

interface RegistryEntry {
  name: string
  owner: string
  repo: string
  subpath?: string
  ref: string
  description: string
  tags: string[]
}

function buildEntry(opts: {
  name: string
  owner: string
  repo: string
  ref: string
  subpath: string
  description: string
  tags: string[]
}): RegistryEntry {
  const entry: RegistryEntry = {
    name: opts.name,
    owner: opts.owner,
    repo: opts.repo,
    ref: opts.ref,
    description: opts.description,
    tags: opts.tags,
  }
  if (opts.subpath) entry.subpath = opts.subpath
  return entry
}

function buildIssueUrl(entry: RegistryEntry): string {
  const title = `registry: add ${entry.name}`
  const body = `## Experience

- **Name (for \`oe install <name>\`):** \`${entry.name}\`
- **GitHub repo:** \`https://github.com/${entry.owner}/${entry.repo}\`
- **Pinned ref (tag preferred):** \`${entry.ref}\`
- **Subpath (if monorepo):** \`${entry.subpath ?? '(none)'}\`
- **One-line description:** \`${entry.description}\`
- **Tags:** \`${entry.tags.join(', ')}\`

## Generated registry entry

\`\`\`json
${JSON.stringify(entry, null, 2)}
\`\`\`

## Checklist

- [ ] The repo contains a working \`experience.yaml\` at the root or subpath above.
- [ ] The repo has a README with: what the flow does, prereqs, one example run command.
- [ ] The repo has a mocked-LLM or smoke test in \`e2e/\` or \`tests/\`.
- [ ] The pinned ref is a tag or specific SHA (not just \`main\`).
- [ ] License is OSI-approved.
- [ ] The flow works against \`@openexpertise/cli@^0.1.0\`.

## How will this be useful

(Describe the use case in 1-2 sentences.)

## Maintainer commitment

(Will you keep this updated as OE evolves? At least one re-test per minor release of OpenExpertise is the norm.)

---

_Generated by \`oe submit\` from \`@openexpertise/cli\`._
`

  // GitHub issue URL with template + pre-filled title/body
  const params = new URLSearchParams({
    template: 'experience_submission.md',
    title,
    body,
  })
  return `https://github.com/xingchengxu/OpenExpertise/issues/new?${params.toString()}`
}

function openBrowser(url: string): boolean {
  const cmd =
    process.platform === 'darwin' ? 'open' : process.platform === 'win32' ? 'start' : 'xdg-open'
  const args = process.platform === 'win32' ? ['', url] : [url]
  const r = spawnSync(cmd, args, { stdio: 'ignore', timeout: 10000 })
  return r.status === 0
}

export async function submitCommand(opts: SubmitOpts): Promise<number> {
  const expPath = resolve(opts.path ?? '.')
  const yamlPath = join(expPath, 'experience.yaml')

  if (!existsSync(yamlPath)) {
    process.stderr.write(
      `${RED}✗${RESET} experience.yaml not found at ${yamlPath}\n` +
        `  Run \`oe submit\` from inside an experience directory, or pass the path as an argument.\n`,
    )
    return 1
  }

  // Validate
  const yamlContent = readFileSync(yamlPath, 'utf8')
  let spec: { name: string; description: string | undefined }
  try {
    const parsed = parseExperienceYaml(yamlContent)
    spec = { name: parsed.name, description: parsed.description }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    process.stderr.write(`${RED}✗${RESET} experience.yaml failed validation:\n  ${msg}\n`)
    return 1
  }
  process.stdout.write(`${GREEN}✓${RESET} experience.yaml validates\n`)

  // Detect repo info (unless overridden)
  const remote = detectGitRemote(expPath)
  if (!remote) {
    process.stderr.write(
      `${RED}✗${RESET} could not detect a github remote in ${expPath}.\n` +
        `  Make sure \`git remote get-url origin\` returns a github.com URL.\n` +
        `  Push to a public GitHub repo first, then re-run \`oe submit\`.\n`,
    )
    return 1
  }
  process.stdout.write(`${GREEN}✓${RESET} Git remote: github.com/${remote.owner}/${remote.repo}\n`)

  const refInfo = detectGitRef(expPath)
  const ref = opts.ref ?? refInfo.ref
  if (opts.ref) {
    process.stdout.write(`${GREEN}✓${RESET} Ref (overridden): ${ref}\n`)
  } else if (refInfo.isTag) {
    process.stdout.write(`${GREEN}✓${RESET} Ref: ${ref} (tag at HEAD)\n`)
  } else {
    process.stdout.write(
      `${YELLOW}⚠${RESET} Ref: ${ref} (not a tag — installs will not be reproducible)\n`,
    )
  }

  const detectedSubpath = detectSubpath(expPath, yamlPath)
  const subpath = opts.subpath ?? detectedSubpath
  if (subpath) {
    process.stdout.write(`${GREEN}✓${RESET} Subpath: ${subpath}\n`)
  }

  const name = opts.name ?? spec.name
  const description = opts.description ?? spec.description ?? ''
  if (!description) {
    process.stdout.write(
      `${YELLOW}⚠${RESET} No description (add \`description:\` to experience.yaml or pass --description)\n`,
    )
  } else {
    process.stdout.write(`${GREEN}✓${RESET} Description from experience.yaml\n`)
  }

  const tags = (opts.tags ?? '')
    .split(',')
    .map((t) => t.trim())
    .filter((t) => t.length > 0)
  if (tags.length === 0) {
    process.stdout.write(
      `${YELLOW}⚠${RESET} No tags (pass --tags <a,b,c> to help discoverability)\n`,
    )
  }

  const entry = buildEntry({
    name,
    owner: remote.owner,
    repo: remote.repo,
    ref,
    subpath,
    description: description || '<TODO: add a one-sentence description>',
    tags: tags.length > 0 ? tags : ['<TODO: add-tags>'],
  })

  process.stdout.write(`\n${BOLD}Generated registry entry for "${name}":${RESET}\n\n`)
  process.stdout.write(JSON.stringify(entry, null, 2))
  process.stdout.write('\n')

  // Output to file
  if (opts.output) {
    writeFileSync(opts.output, JSON.stringify(entry, null, 2))
    process.stdout.write(`\n${GREEN}✓${RESET} wrote registry entry to ${opts.output}\n`)
    return 0
  }

  // Dry-run
  if (opts.dryRun) {
    process.stdout.write(`\n${DIM}(dry-run: no submission opened)${RESET}\n`)
    return 0
  }

  // Build + open the GH issue URL
  const url = buildIssueUrl(entry)
  process.stdout.write(`\n${BOLD}Opening pre-filled submission issue…${RESET}\n`)
  process.stdout.write(`${DIM}${url.substring(0, 100)}…${RESET}\n\n`)

  const opened = openBrowser(url)
  if (!opened) {
    process.stdout.write(
      `${YELLOW}Could not open browser automatically. Open this URL manually:${RESET}\n${url}\n`,
    )
  } else {
    process.stdout.write(`${DIM}(if your browser did not open, copy the URL above)${RESET}\n`)
  }

  return 0
}
