import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { LLMClient, LLMTool } from '@openexpertise/core'
import type { ExperienceSpec } from '@openexpertise/schema'

const HERE = dirname(fileURLToPath(import.meta.url))

export type EvolutionOperation = 'add-node' | 'tune-param' | 'add-dataset-case'
export type EvolutionConfidence = 'high' | 'medium' | 'low'

export interface EvolutionProposal {
  operation: EvolutionOperation
  confidence: EvolutionConfidence
  rationale: string
  diff: string // unified diff snippet (for add-node / tune-param) OR JSON array (for add-dataset-case)
  title: string
}

export interface EvolutionAdvisorOpts {
  client: LLMClient
  model?: string
}

export interface EvolutionInput {
  experienceSpec: ExperienceSpec
  experienceYamlSource: string
  runEvents: unknown[] // jsonl lines parsed
  stateDiff: Array<{ field: string; before: unknown; after: unknown }>
}

const PROPOSAL_SCHEMA = {
  type: 'object',
  required: ['proposals'],
  properties: {
    proposals: {
      type: 'array',
      maxItems: 5,
      items: {
        type: 'object',
        required: ['operation', 'confidence', 'title', 'rationale', 'diff'],
        properties: {
          operation: { type: 'string', enum: ['add-node', 'tune-param', 'add-dataset-case'] },
          confidence: { type: 'string', enum: ['high', 'medium', 'low'] },
          title: { type: 'string' },
          rationale: { type: 'string' },
          diff: { type: 'string' },
        },
      },
    },
  },
}

export class EvolutionAdvisor {
  constructor(private readonly opts: EvolutionAdvisorOpts) {}

  async analyze(input: EvolutionInput): Promise<EvolutionProposal[]> {
    const systemPath = resolve(HERE, 'prompts/proposal.md')
    const system = readFileSync(systemPath, 'utf8')
    const userPayload = {
      experience_yaml: input.experienceYamlSource,
      run_event_count: input.runEvents.length,
      state_diff: input.stateDiff,
      // a small slice of events so we don't blow the context budget
      sample_events: input.runEvents.slice(0, 30),
    }
    const tool: LLMTool = {
      name: 'structured_output',
      description: 'Return a list of evolution proposals matching the schema',
      input_schema: PROPOSAL_SCHEMA,
    }
    const result = await this.opts.client.complete({
      model: this.opts.model ?? 'claude-sonnet-4-5',
      system,
      messages: [{ role: 'user', content: JSON.stringify(userPayload, null, 2) }],
      tools: [tool],
      max_tokens: 8192,
    })
    const call = result.tool_calls?.find((c) => c.name === 'structured_output')
    if (!call) return []
    const input2 = call.input as { proposals?: EvolutionProposal[] }
    return input2.proposals ?? []
  }

  renderMarkdown(proposals: EvolutionProposal[], runId: string): string {
    const lines: string[] = []
    lines.push(`# Evolution Proposals for run \`${runId}\``)
    lines.push('')
    lines.push(`Generated by OpenExpertise EvolutionAdvisor. Review each suggestion`)
    lines.push(`and \`git apply\` the diff blocks you accept; runtime never auto-applies.`)
    lines.push('')
    if (proposals.length === 0) {
      lines.push('_No proposals generated for this run._')
      return lines.join('\n') + '\n'
    }
    for (let i = 0; i < proposals.length; i++) {
      const p = proposals[i]!
      lines.push(`## ${i + 1}. ${p.title} _(${p.operation}, confidence: ${p.confidence})_`)
      lines.push('')
      lines.push(p.rationale)
      lines.push('')
      lines.push('```diff')
      lines.push(p.diff)
      lines.push('```')
      lines.push('')
    }
    return lines.join('\n')
  }
}
